//
// Created by alex on 29/9/25.
//

#ifndef THREADS_2025C2_ALEXGUTTLEIN_COMMON_PROTECTEDQUEUE_H
#define THREADS_2025C2_ALEXGUTTLEIN_COMMON_PROTECTEDQUEUE_H

#endif  // THREADS_2025C2_ALEXGUTTLEIN_COMMON_PROTECTEDQUEUE_H
